version: 2.1

orbs: 
  node: circleci/node@5.0.2


jobs:
  build:
    docker:
      - image: cimg/node:17.2.0
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm

      - run:
          command: npm install
          name: Install packages

      - run:
          command: npm install @angular/cli
          name: Install Angular

      - run:
          command: ng build
          name: Build apps

workflows:
  build:
    jobs:
      - build
